name: entity-env
channels:
    - defaults
    - anaconda
    - conda-forge
dependencies:
  - beautifulsoup4==4.8.1 # 4.10.0 has noarch
  - flask==1.1.1 # any here or later is good
  - python
  - requests==2.26.0
  - spacy==3.1.0
  - spacy-model-en_core_web_sm==3.1.0
